try {
  print();
} catch {
  console.log('Error');
}
